version: "3.8"
services:
  main:
    image: rms_cctv_collector_test
    container_name: rms_cctv_collector_test
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
#  fastapi:
#    image: rms_cctv_collector_test
#    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload
#    container_name: rms_cctv_collector_test
#    build:
#      context: .
#      dockerfile: ./Dockerfile
#    restart: always
#    env_file:
#      - .env